services:
  front:
    build:
      context: ./fso-graphql-front
      dockerfile: Dockerfile
    container_name: fullstack-front-prod
    stdin_open: true
  back:
    build:
      context: ./fso-graphql-back
      dockerfile: Dockerfile
    container_name: fullstack-back-prod
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: nginx-reverse-proxy-prod
    depends_on:
      - front
      - back
